/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BecomeArtistRouteImport } from './routes/become-artist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistDashboardRouteImport } from './routes/artist-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackTrackIdRouteImport } from './routes/track.$trackId'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeArtistRoute = BecomeArtistRouteImport.update({
  id: '/become-artist',
  path: '/become-artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistDashboardRoute = ArtistDashboardRouteImport.update({
  id: '/artist-dashboard',
  path: '/artist-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTrackIdRoute = TrackTrackIdRouteImport.update({
  id: '/track/$trackId',
  path: '/track/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/shorts': typeof ShortsRoute
  '/upload': typeof UploadRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/track/$trackId': typeof TrackTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/shorts': typeof ShortsRoute
  '/upload': typeof UploadRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/track/$trackId': typeof TrackTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artist-dashboard': typeof ArtistDashboardRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/chat': typeof ChatRoute
  '/discover': typeof DiscoverRoute
  '/downloads': typeof DownloadsRoute
  '/library': typeof LibraryRoute
  '/members': typeof MembersRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/shorts': typeof ShortsRoute
  '/upload': typeof UploadRoute
  '/post/$postId': typeof PostPostIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/track/$trackId': typeof TrackTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artist-dashboard'
    | '/auth'
    | '/become-artist'
    | '/chat'
    | '/discover'
    | '/downloads'
    | '/library'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/shorts'
    | '/upload'
    | '/post/$postId'
    | '/profile/edit'
    | '/track/$trackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/artist-dashboard'
    | '/auth'
    | '/become-artist'
    | '/chat'
    | '/discover'
    | '/downloads'
    | '/library'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/shorts'
    | '/upload'
    | '/post/$postId'
    | '/profile/edit'
    | '/track/$trackId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artist-dashboard'
    | '/auth'
    | '/become-artist'
    | '/chat'
    | '/discover'
    | '/downloads'
    | '/library'
    | '/members'
    | '/notifications'
    | '/profile'
    | '/shorts'
    | '/upload'
    | '/post/$postId'
    | '/profile/edit'
    | '/track/$trackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArtistDashboardRoute: typeof ArtistDashboardRoute
  AuthRoute: typeof AuthRoute
  BecomeArtistRoute: typeof BecomeArtistRoute
  ChatRoute: typeof ChatRoute
  DiscoverRoute: typeof DiscoverRoute
  DownloadsRoute: typeof DownloadsRoute
  LibraryRoute: typeof LibraryRoute
  MembersRoute: typeof MembersRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ShortsRoute: typeof ShortsRoute
  UploadRoute: typeof UploadRoute
  PostPostIdRoute: typeof PostPostIdRoute
  TrackTrackIdRoute: typeof TrackTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-artist': {
      id: '/become-artist'
      path: '/become-artist'
      fullPath: '/become-artist'
      preLoaderRoute: typeof BecomeArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist-dashboard': {
      id: '/artist-dashboard'
      path: '/artist-dashboard'
      fullPath: '/artist-dashboard'
      preLoaderRoute: typeof ArtistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/post/$postId': {
      id: '/post/$postId'
      path: '/post/$postId'
      fullPath: '/post/$postId'
      preLoaderRoute: typeof PostPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArtistDashboardRoute: ArtistDashboardRoute,
  AuthRoute: AuthRoute,
  BecomeArtistRoute: BecomeArtistRoute,
  ChatRoute: ChatRoute,
  DiscoverRoute: DiscoverRoute,
  DownloadsRoute: DownloadsRoute,
  LibraryRoute: LibraryRoute,
  MembersRoute: MembersRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ShortsRoute: ShortsRoute,
  UploadRoute: UploadRoute,
  PostPostIdRoute: PostPostIdRoute,
  TrackTrackIdRoute: TrackTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
